#!/usr/bin/env python3
"""dual_island_targets.py -- enumerate the individual-island design targets.

John's design plan: take the dual-island mAb epitopes, scaffold each of their two islands
*individually*, and keep the top-5 designs per island. This script defines that target set
from the DP3 ledger so the design run (and the manuscript) rests on one reproducible table.

Definitions (all read from dp2.parquet, never invented):
- An *island* is one fixed-coordinate A-segment of the RFD3 contig string, e.g. the contig
  `15-15/A1-16/57-57/A81-81/15-15` has two islands, A1-16 (16 residues) and A81-81 (1).
- A *dual-island epitope* is a ledger id with `epitope_chunks == 2` (exactly two A-segments).
- *Island size* is the A-segment span length (residues), not the epitope-contact count.

Selection rule: a single-residue island cannot be presented on its own, so islands of size 1
are *skipped* (scaffold=False) -- but the epitope's other island is still scaffolded. No
epitope is dropped outright; only the degenerate island is.

Output:
- results/dual_island_targets.csv -- one row per island (two per epitope) with its span,
  size, the partner island's size, and the scaffold/skip decision.
- manuscript/tables/dual_island_targets.tex -- a generated longtable of per-epitope island
  lengths (size-1 skipped islands marked), \input by the manuscript. Never hand-edited.

Regenerate:
  python3 episcaf_analysis/dual_island_targets.py \
      --dp2 ../known_antigen/analysis/full_run/dp2.parquet \
      --out results/dual_island_targets.csv \
      --tex manuscript/tables/dual_island_targets.tex
"""
from __future__ import annotations
import argparse
import re
from pathlib import Path

import pandas as pd

A_SEGMENT = re.compile(r"A(\d+)-(\d+)")
MIN_ISLAND_SIZE = 2  # an island of 1 residue cannot be presented on its own


def islands_from_contig(contig_string: str) -> list[tuple[int, int]]:
    """Return the list of (start, end) 1-based A-segment spans in a contig string."""
    return [(int(a), int(b)) for a, b in A_SEGMENT.findall(contig_string)]


def _isl(span: str, size: int) -> str:
    """LaTeX cell for one island; size-1 (skipped) islands carry a dagger."""
    span_tex = span.replace("-", "--")
    dagger = r"$^\dagger$" if size < MIN_ISLAND_SIZE else ""
    return f"\\texttt{{{span_tex}}} ({size}){dagger}"


def _write_tex(out: pd.DataFrame, path: Path, n_epitopes: int, n_targets: int,
               n_skipped: int) -> None:
    """Emit a generated longtable of per-epitope island lengths (do not hand-edit)."""
    per_epi = []
    for eid, g in out.groupby("id"):
        g = g.sort_values("island_index")
        (s1, z1), (s2, z2) = zip(g["island"], g["island_size"])
        designed = "both" if g["scaffold"].all() else "larger only"
        per_epi.append((min(z1, z2), eid, _isl(s1, z1), _isl(s2, z2), designed))
    per_epi.sort(key=lambda r: (r[0], r[1]))  # smallest island first -> skips on top

    lines = [
        "% GENERATED by episcaf_analysis/dual_island_targets.py -- do not hand-edit.",
        r"\begin{longtable}{llll}",
        r"\caption{Island lengths of the \num{46} dual-island DP3 epitopes, the input to the "
        r"per-island design run (Section~\ref{sec:perisland}). Each island is one contig "
        r"\texttt{A}-segment; the value in parentheses is its length in residues. An island "
        r"marked $^\dagger$ is a single residue and is skipped (it cannot be presented alone); "
        r"the epitope's other island is still scaffolded. Of the \num{92} islands, "
        f"\\num{{{n_targets}}} are scaffolded (size $\\ge 2$) and \\num{{{n_skipped}}} skipped.}}"
        r"\label{tab:dualisland}\\",
        r"\toprule",
        r"epitope & island 1 & island 2 & designed \\",
        r"\midrule",
        r"\endfirsthead",
        r"\multicolumn{4}{c}{\tablename~\thetable\ (continued)}\\",
        r"\toprule epitope & island 1 & island 2 & designed \\ \midrule \endhead",
        r"\bottomrule \endfoot",
    ]
    for _, eid, i1, i2, designed in per_epi:
        lines.append(f"\\texttt{{{eid.replace('_', chr(92)+'_')}}} & {i1} & {i2} & {designed} \\\\")
    lines.append(r"\end{longtable}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dp2", type=Path,
                    default=Path("../known_antigen/analysis/full_run/dp2.parquet"))
    ap.add_argument("--out", type=Path, default=Path("results/dual_island_targets.csv"))
    ap.add_argument("--tex", type=Path,
                    default=Path("manuscript/tables/dual_island_targets.tex"))
    args = ap.parse_args()

    df = pd.read_parquet(args.dp2)
    dual = df[df.epitope_chunks == 2].drop_duplicates("id")

    rows = []
    for _, r in dual.iterrows():
        segs = islands_from_contig(r["contig_string"])
        if len(segs) != 2:
            raise ValueError(f"{r['id']}: epitope_chunks==2 but {len(segs)} A-segments "
                             f"in contig {r['contig_string']!r}")
        sizes = [b - a + 1 for a, b in segs]
        for idx, ((a, b), size) in enumerate(zip(segs, sizes), start=1):
            rows.append({
                "id": r["id"],
                "contig_string": r["contig_string"],
                "island": f"A{a}-{b}",
                "island_index": idx,
                "island_size": size,
                "partner_size": sizes[1] if idx == 1 else sizes[0],
                "scaffold": size >= MIN_ISLAND_SIZE,
            })

    out = pd.DataFrame(rows).sort_values(["scaffold", "island_size", "id", "island_index"],
                                         ascending=[False, False, True, True])
    args.out.parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(args.out, index=False)

    n_epitopes = out["id"].nunique()
    n_targets = int(out["scaffold"].sum())
    skipped = out.loc[~out["scaffold"]]

    if args.tex:
        _write_tex(out, args.tex, n_epitopes, n_targets, len(skipped))
        print(f"wrote {args.tex}")

    print(f"wrote {args.out}")
    print(f"  dual-island epitopes      : {n_epitopes}")
    print(f"  islands total             : {len(out)}")
    print(f"  scaffolded (size>=2)      : {n_targets}  -> {n_targets} x 5 = {n_targets*5} designs")
    print(f"  skipped size-1 islands    : {len(skipped)}  "
          f"(in {', '.join(skipped['id'])})")


if __name__ == "__main__":
    main()
