#!/usr/bin/env python3
"""filter_c6_depth.py -- reduce the C6 controls to the top-N ranked base designs per antibody.

C6 controls are mutants of the C1 top-k designs. To ship controls only for the top-N (John, 2026-07-21:
top-15, to save space -- C6 was the biggest block), we FILTER the already-built C6 rather than re-running
build_c6_mutants: the scaffold-disruption control places hexamers with a global RNG, so re-running on a
different input set RE-RANDOMIZES those sequences -- which would then not match what the oligo encoder
already encoded. Filtering keeps the exact encoded sequences, so the order file can be regenerated by
sequence with no re-encode (stage07_order_file --by-sequence).

Each C6 design_ID is `<base_C1_predID><mutation-suffix>`; we strip the suffix, join the base to the C1
ranked table for its rank_in_group, and keep base rank <= N.

Usage:
  python scripts/filter_c6_depth.py --in <top20 C6.csv> --ranked results/dp4_C1_whole_epitope_ranked.top20.csv \
      --depth 15 --out results/dp4_C6_controls.csv
"""
from __future__ import annotations
import argparse
import pandas as pd

SUFFIXES = ("_epitopeIsland1Mut>A", "_epitopeIsland2Mut>A",
            "_scaffoldMutX4", "_scaffoldMutX3", "_scaffoldMutX2", "_scaffoldMutX1")


def base_of(design_id: str) -> str:
    s = str(design_id)
    for suf in SUFFIXES:
        if s.endswith(suf):
            return s[: -len(suf)]
    return s


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--in", dest="inp", required=True, help="the built (top-k) C6 controls CSV to filter")
    ap.add_argument("--ranked", default="results/dp4_C1_whole_epitope_ranked.top20.csv",
                    help="C1 ranked table with predID + rank_in_group")
    ap.add_argument("--depth", type=int, default=15)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    c6 = pd.read_csv(args.inp, low_memory=False)
    rk = pd.read_csv(args.ranked, low_memory=False)[["predID", "rank_in_group"]]
    c6["_base"] = c6["design_ID"].map(base_of)
    m = c6.merge(rk, left_on="_base", right_on="predID", how="left")
    n_unmatched = int(m["rank_in_group"].isna().sum())
    if n_unmatched:
        print(f"[filter_c6] WARNING: {n_unmatched} C6 rows did not match a C1 rank (dropped)")
    out = m[m["rank_in_group"] <= args.depth].drop(columns=["_base", "predID", "rank_in_group"])
    out.to_csv(args.out, index=False)
    fl = out["design_ID"].astype(str).map(
        lambda x: "island1" if "Island1Mut" in x else "island2" if "Island2Mut" in x
        else "scaffold" if "scaffoldMut" in x else "other")
    print(f"[filter_c6] {len(c6)} -> {len(out)} controls at top-{args.depth} -> {args.out}")
    print("[filter_c6] by flavor:", fl.value_counts().to_dict())


if __name__ == "__main__":
    main()
